---
name: test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  tests:
    name: "Tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - name: "Install Python"
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.11"
      - name: "Install dependencies"
        run: "pip install -r requirements-dev.txt"
      - name: "Lint"
        run: "pylint frontend backend"
